#!/bin/bash
echo -e "Please provide the filename you want you want to create: \c"
read -r file
touch $file.sh
echo '#!bin/bash' > $file.sh
echo '#Purpose:' >> $file.sh
echo '#Version:' >> $file.sh
echo '#Created Date:' `date` >> $file.sh
echo '#Modified Date:'  >> $file.sh
echo '#Author: sochtech@codedemon:~$ id' >> $file.sh
echo '# START #' >> $file.sh
echo '# END #' >> $file.sh
